version: '3'
services:

 send_message-nodecore:
  image: registry.gitlab.com/crowdwiz/send_message/nodecore:crowdwiz-dev
  restart: always
  ports:
   - "0.0.0.0:1776:8089"
   - "0.0.0.0:11011:11011" 
  volumes:
  - "./witness_node_data_dir:/var/lib/crowdwiz"
  networks:
      - node-net

 nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "0.0.0.0:9100:9100"
    networks:
      - monitor-net

 cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - monitor-net

networks:
  monitor-net:
  node-net:
    driver: bridge
